on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
      - 'release/**'
    paths-ignore:
      - '/*.sh'
      - '/.*'
      - '/_*'
      - 'Brewfile'
      - 'docs/**'
      - '**.adoc'
      - '**.md'
      - '**.nix'
      - 'flake.lock'
      - 'version.txt'
      - '.github/workflows/*.yml'
      - '!.github/workflows/build.yml'
  pull_request:
    paths-ignore:
      - '/*.sh'
      - '/.*'
      - '/_*'
      - 'Brewfile'
      - 'docs/**'
      - '**.adoc'
      - '**.md'
      - '**.nix'
      - 'flake.lock'
      - 'version.txt'

# Add required permissions for OIDC and attestations
permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  build:
    # uses: LOWPROKB/zmk/.github/workflows/build-user-config.yml@corne-ish-zen-v2
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  attest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download merged firmware artifact
        uses: actions/download-artifact@v4
        with:
          name: firmware
          path: ./firmware

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: ./firmware
